# Generated by Django 2.1.7 on 2019-06-19 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ImageRecog', '0008_auto_20190620_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerquest',
            name='questitem',
            field=models.CharField(choices=[('airplane', 'Airplane'), ('boat', 'Boat'), ('computer_mouse', 'Computer Mouse'), ('flower', 'Flower'), ('fridge', 'Fridge'), ('house', 'House'), ('playground', 'Playground'), ('pond', 'Pond'), ('road', 'Road'), ('rubbish_bin', 'Rubbish Bin'), ('sidewalk', 'Sidewalk'), ('stop_sign', 'Stop Sign'), ('tree', 'Tree'), ('truck', 'Truck'), ('vending_machine', 'Vending Machine')], default='fridge', max_length=100),
        ),
        migrations.AlterField(
            model_name='quests',
            name='quest1',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quest1', to='ImageRecog.PlayerQuest'),
        ),
        migrations.AlterField(
            model_name='quests',
            name='quest2',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quest2', to='ImageRecog.PlayerQuest'),
        ),
        migrations.AlterField(
            model_name='quests',
            name='quest3',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quest3', to='ImageRecog.PlayerQuest'),
        ),
    ]
