# Generated by Django 2.1.7 on 2019-06-20 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageRecog', '0009_auto_20190620_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerquest',
            name='lastused',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerquest',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='playerquest',
            name='questitem',
            field=models.CharField(choices=[('airplane', 'Airplane'), ('boat', 'Boat'), ('computer_mouse', 'Computer Mouse'), ('flower', 'Flower'), ('fridge', 'Fridge'), ('house', 'House'), ('playground', 'Playground'), ('pond', 'Pond'), ('road', 'Road'), ('rubbish_bin', 'Rubbish Bin'), ('sidewalk', 'Sidewalk'), ('stop_sign', 'Stop Sign'), ('tree', 'Tree'), ('truck', 'Truck'), ('vending_machine', 'Vending Machine')], default='computer_mouse', max_length=100),
        ),
    ]
