# Generated by Django 2.1.7 on 2019-06-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageRecog', '0011_auto_20190620_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerquest',
            name='questitem',
            field=models.CharField(choices=[('airplane', 'Airplane'), ('boat', 'Boat'), ('computer_mouse', 'Computer Mouse'), ('flower', 'Flower'), ('fridge', 'Fridge'), ('house', 'House'), ('playground', 'Playground'), ('pond', 'Pond'), ('road', 'Road'), ('rubbish_bin', 'Rubbish Bin'), ('sidewalk', 'Sidewalk'), ('stop_sign', 'Stop Sign'), ('tree', 'Tree'), ('truck', 'Truck'), ('vending_machine', 'Vending Machine')], default='vending_machine', max_length=100),
        ),
    ]
