# Generated by Django 2.1.7 on 2019-04-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0002_auto_20190430_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='useravatar',
            field=models.ImageField(blank=True, upload_to='avatars/'),
        ),
    ]
