# Generated by Django 2.1.7 on 2019-04-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0003_auto_20190430_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='useravatar',
            field=models.ImageField(blank=True, default='avatars/noimg.jpg', upload_to='avatars/'),
        ),
    ]
