# Generated by Django 2.1.7 on 2019-07-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0005_auto_20190621_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='useravatar',
            field=models.ImageField(blank=True, default='avatars/blank.jpg', upload_to='avatars/'),
        ),
    ]
