# Generated by Django 2.1.7 on 2019-07-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0006_auto_20190715_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='useravatar',
            field=models.ImageField(blank=True, default='avatars/blank.png', upload_to='avatars/'),
        ),
    ]
