# Generated by Django 2.2.1 on 2019-08-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0007_auto_20190723_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), (None, 'Genderless')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='privated',
            field=models.BooleanField(default=False),
        ),
    ]
