# Generated by Django 2.2.1 on 2019-08-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0008_auto_20190802_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('None', 'Genderless')], max_length=1, null=True),
        ),
    ]
