# Generated by Django 2.2.1 on 2019-07-25 05:20

import Rifts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rifts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riftimage',
            name='image',
            field=models.ImageField(null=True, upload_to=Rifts.models.RiftImagePath),
        ),
    ]
