# Generated by Django 2.1.7 on 2019-07-25 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rifts', '0002_riftimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rift',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
