# Generated by Django 2.1.7 on 2019-07-25 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rifts', '0004_auto_20190725_1800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rift',
            options={'ordering': ('upload_date',)},
        ),
    ]
