# Generated by Django 2.1.7 on 2019-07-25 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rifts', '0005_auto_20190725_2115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rift',
            options={'ordering': ('-upload_date',)},
        ),
    ]
