# Generated by Django 2.1.7 on 2019-07-25 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Rifts', '0006_auto_20190725_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiftRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.BooleanField(null=True)),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rifts.Rift')),
            ],
        ),
    ]
