# Generated by Django 2.2.1 on 2019-07-26 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rifts', '0008_auto_20190725_2233'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='riftrating',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='riftrating',
            constraint=models.UniqueConstraint(fields=('rater', 'rating'), name='Self-Follow'),
        ),
    ]
