# Generated by Django 2.2.1 on 2019-07-26 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rifts', '0009_auto_20190727_0754'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='riftrating',
            name='Self-Follow',
        ),
        migrations.AddConstraint(
            model_name='riftrating',
            constraint=models.UniqueConstraint(fields=('rater', 'rating'), name='Rate-Once'),
        ),
    ]
