# Generated by Django 2.2.1 on 2019-08-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rifts', '0010_auto_20190727_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='rift',
            name='format',
            field=models.BooleanField(default=False),
        ),
    ]
