# Generated by Django 2.2.1 on 2019-08-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rifts', '0011_rift_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='rift',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
