# Generated by Django 2.2.1 on 2019-08-02 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rifts', '0012_rift_edited'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rift',
            options={},
        ),
    ]
