# Generated by Django 2.2.1 on 2019-08-02 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rifts', '0015_auto_20190802_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rift',
            options={'ordering': ('-upload_date',)},
        ),
    ]
