# Generated by Django 2.2.1 on 2019-07-26 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PixoUM', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('follower', 'following'), name='Self-Follow'),
        ),
    ]
