# Generated by Django 2.2.1 on 2019-07-26 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PixoUM', '0002_auto_20190727_0754'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='Self-Follow',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('follower', 'following'), name='Follow-Once'),
        ),
    ]
