# Generated by Django 2.2.1 on 2019-07-03 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlayerData', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerdata',
            options={'ordering': ['level', 'xp']},
        ),
    ]
